Add ecs-bare-metal-instance module
alibabacloud-automation/terraform-alicloud-ecs-bare-metal-instance pull request #1
Opened 2020-02-22 14:34 UTC by Rich-yi

2020-02-22 15:06 UTC, zql-tqy commented on README-CN.md
> +本 Terraform 模块将用于在阿里云上创建神龙服务器实例的Terraform模块。
这句话调整一下吧，不太通顺

2020-02-22 15:06 UTC, zql-tqy commented on README-CN.md
> +神龙服务器有cpu和gpu两种分类，你可以通过bare_metal_classification字段取值’cpu‘或’gpu‘以创建不同神龙服务器。
readme里面用的应该是这个  ` 吧

2020-02-22 15:06 UTC, zql-tqy commented on README.md
> +
缺了句描述

2020-02-22 15:06 UTC, zql-tqy commented on varibales.tf
> +  description = "An KMS encrypts password used to an instance. It is conflicted with `password`."
'password'下面存在

2020-02-22 15:06 UTC, zql-tqy commented on varibales.tf
> +  default     = ""
这几个没有type

2020-02-22 15:06 UTC, zql-tqy commented on varibales.tf
> +    include_data_disks = true
map(string)的话应该是 “true”吧

2020-02-22 15:06 UTC, zql-tqy commented on main.tf
> +
多余的空行删掉吧

2020-02-22 15:06 UTC, zql-tqy commented on README.md
> +  instance_charge_type        = "PrePaid"
如果module中有不同resource的参数，用空行隔开

2020-02-24 06:43 UTC, xiaozhu36 requested changes

2020-02-24 06:43 UTC, xiaozhu36 commented on main.tf
> +  shared_credentials_file = var.shared_credentials_file
这个写法不对

2020-02-24 06:43 UTC, xiaozhu36 commented on outputs.tf
> +  value       = concat(module.ecs-instance.this_public_ip, [""])[0]
这个本身就是支持多个的，因此直接输出list就行

2020-02-24 06:43 UTC, xiaozhu36 commented on varibales.tf
> +variable "bare_metal_classification" {
改为 bare_metal_type

2020-02-24 06:43 UTC, xiaozhu36 commented on outputs.tf
> +output "this_instance_bare_metal_classification" {
这个不用输出

2020-02-24 06:43 UTC, xiaozhu36 commented on varibales.tf
> +  default     = "ecs.ebmgn6e"
这个默认值好像跟代码中设置的不一样啊

2020-02-24 06:43 UTC, xiaozhu36 commented on varibales.tf
> +    Source  = "alibaba/ecs-instance/alicloud//modules/bare-metal"
这个tags会跟 ecs-isntance的默认的tag冲突么？有测试过么

2020-02-24 11:32 UTC, xiaozhu36 requested changes

2020-02-24 11:32 UTC, xiaozhu36 commented on main.tf
> +  instance_type_families    = var.bare_metal_type != true ? ["ecs.ebmgn6v", "ecs.ebmgn6i", "ecs.sccgn6ne", "ecs.ebmgn6e", "ecs.sccgn6"] : ["ecs.ebmc6", "ecs.ebmg6", "ecs.ebmr6", "ecs.ebmhfc6", "ecs.e
var.bare_metal_type != true 这个判断不对吧，bare_metal_type 不是string么？
这个地方这样写，gpu和cpu的枚举分别存储为两个local变量，然后要判断指定的family跟type对应的families是否匹配

2020-02-24 11:32 UTC, xiaozhu36 commented on main.tf
> +  instance_type_family = var.instance_type_family != "" && contains(local.instance_type_families, var.instance_type_family) ? var.instance_type_family : "ecs.ebmc6"
这个地方要判断，如果是gpu，那么指定的family也应该在gpu的families中；cpu也一样
如果不匹配或者不在列举值中，要设置为 “null”，这样表示找不到对应的familiy，然后在执行的时候报错。

2020-02-24 11:32 UTC, xiaozhu36 commented on outputs.tf
> +}
zone，system disk type和size也输出下；

2020-02-24 12:49 UTC, xiaozhu36 requested changes

2020-02-24 12:49 UTC, xiaozhu36 commented on varibales.tf
> +  description = "Whether to choose to create a bare metal instance of cpu classification. Value: `cpu`, `gpu`."
'cpu', 'gpu'

2020-02-24 12:49 UTC, xiaozhu36 commented on main.tf
> +  gpu_families           = ["ecs.ebmgn6v", "ecs.ebmgn6i", "ecs.sccgn6ne", "ecs.ebmgn6e", "ecs.sccgn6"]
这个逻辑不对吧，
bare_metal_type不用
instance_type_families = var.bare_metal_type == "gpu" ？ local.gpu_families : local.cpu_families

2020-02-24 12:49 UTC, xiaozhu36 commented on main.tf
> +  instance_type_family = var.instance_type_family != "" && contains(local.instance_type_families, var.instance_type_family) ? var.instance_type_family : "ecs.ebmc6"
instance_type_family = contains(concat(local.cpu_families, local.gpu_families), var.instance_type_family) ? var.instance_type_family : "null"

2020-02-24 12:49 UTC, xiaozhu36 commented on examples/complete/main.tf
> +  name                        = "TF-bare-metal"
profile

2020-02-24 12:49 UTC, xiaozhu36 commented on examples/complete/main.tf
> +  region              = var.region
profile

2020-02-24 12:49 UTC, xiaozhu36 commented on examples/complete/main.tf
> +  profile = "Your-Profile-Name"
可以和region一样，直接吧profile直接抽象为一个variable

2020-02-24 13:50 UTC, xiaozhu36 approved these changes

2020-02-24 13:51 UTC, merged